{
 "title": "gnmi",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bgpneighbors",
    "query": "SHOW TAG VALUES FROM \"openconfig_bgp\" WITH KEY = \"neighbor_address\""
   },
   {
    "name": "bgpSources",
    "query": "SHOW TAG VALUES FROM \"openconfig_bgp\" WITH KEY = \"source\""
   },
   {
    "name": "intfvar",
    "query": "SHOW TAG VALUES FROM \"ifcounters\" WITH KEY=\"name\""
   },
   {
    "name": "switchIP",
    "query": "SHOW TAG VALUES FROM \"ifcounters\" WITH KEY=\"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "BGP Neighbors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "neighbor_address" ], "type": "tag" }
     ],
     "measurement": "openconfig_bgp",
     "query": "SELECT last(\"neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received\") AS \"pfxRcvd\", last(\"neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent\") AS \"pfxSent\", last(\"neighbors/neighbor/state/session_state\") AS \"state\", last(\"neighbor_address\"), last(\"neighbors/neighbor/state/peer_as\") AS \"Peer ASN\" FROM \"openconfig_bgp\" WHERE (\"source\" =~ /^$bgpSources$/) AND $timeFilter GROUP BY \"neighbor_address\"",
     "select": [
      [
       {
        "params": [
         "neighbors/neighbor/afi_safis/afi_safi/state/prefixes/received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pfxRcvd" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "neighbors/neighbor/afi_safis/afi_safi/state/prefixes/sent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pfxSent" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "neighbors/neighbor/state/session_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "neighbors/neighbor/state/peer_as"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Peer ASN" ], "type": "alias" }
      ],
      [
       { "params": [ "neighbor_address" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$bgpSources$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU",
     "query": " SELECT \"util\" FROM \"kernel\" WHERE (\"source\" = '10.83.13.139')",
     "select": [
      [
       { "params": [ "util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switchIP$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RAM",
     "query": " SELECT \"util\" FROM \"kernel\" WHERE (\"source\" = '10.83.13.139')",
     "select": [
      [
       { "params": [ "memAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switchIP$/" }
     ]
    }
   ]
  },
  {
   "title": "BitRate In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$intfvar-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) *8 FROM \"ifcounters\" WHERE (\"source\" =~ /^$switchIP$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switchIP$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$intfvar$/" }
     ]
    },
    {
     "alias": "$intfvar-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) *8 FROM \"ifcounters\" WHERE (\"source\" =~ /^$switchIP$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switchIP$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$intfvar$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RAM",
     "query": " SELECT \"util\" FROM \"kernel\" WHERE (\"source\" = '10.83.13.139')",
     "select": [
      [
       { "params": [ "memAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "memAvailable" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "memTotal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switchIP$/" }
     ]
    }
   ]
  }
 ]
}